anay-208/nextjs-hackathon

components.json
package.json
pnpm-lock.yaml
src/app/(home)/page.tsx
src/app/dashboard/journaling/page.tsx
src/app/globals.css
src/lib/utils.ts

Finish Setting Up Frontend Structure

---

src/app/api/journal/count/route.ts

Fix incorrect journal count response

---

README.md

Fix readme is unclear about how to create a db

---

next.config.ts
package.json
pnpm-lock.yaml
src/app/(app)/dashboard/journal/[id]/page.tsx
src/app/(app)/dashboard/journal/[id]/pin.client.tsx
src/app/(app)/dashboard/journal/[id]/sidebar.tsx
src/app/(app)/dashboard/journal/[id]/tiptap-editor.client.tsx
src/app/(app)/dashboard/journal/[id]/tiptap.client.tsx
src/app/(app)/dashboard/journal/card.client.tsx
src/app/(app)/dashboard/journal/constants.ts
src/app/(app)/dashboard/journal/loading.tsx
src/app/(app)/dashboard/journal/page.tsx
src/app/(app)/dashboard/journal/pagination.tsx
src/app/(app)/dashboard/journal/total.client.tsx
src/app/layout.tsx
src/components/ui/sonner.tsx

This does not contain the following
1) Getting all pinned
2) Linking images to backend
Another PR will be made for those

Finish the Functionality Part of the Journal

---

src/app/api/journal/db.ts
src/app/api/journal/types.ts

Add search to journals

---

src/app/(app)/journal/[id]/data.ts
src/app/api/journal/actions.ts
src/app/api/journal/db.ts
src/db/schema.ts

closes #70 
add mood and similar tags

Add tags support to journal entries

---

src/app/api/finance/actions.ts
src/app/api/finance/db.ts

This pull request includes changes to the `src/app/api/finance` module, specifically adding functionality to retrieve a category by its ID. The most important changes are the addition of a new database query function and a corresponding API handler.
* [`src/app/api/finance/db.ts`](diffhunk://#diff-74195402edb16756990a0c66c714be374db2bd3b9bcc42902baf189d7b1a499aR108-R117): Added the `dbGetCategory` function to query the database for a category by its ID and user ID.
* [`src/app/api/finance/actions.ts`](diffhunk://#diff-260fbe41f4f7257f0b40b2ac6e41078ab166248e43cedc83d828118c9c42fe25R9): Imported the `dbGetCategory` function and added the `getCategory` API handler to retrieve a category by its ID. [[1]](diffhunk://#diff-260fbe41f4f7257f0b40b2ac6e41078ab166248e43cedc83d828118c9c42fe25R9) …

Add getCategory function and dbGetCategory query for category retrieval

---

src/app/api/finance/actions.ts
src/app/api/finance/db.ts
src/app/api/finance/types.ts

closes #96 
This pull request introduces enhancements to the transaction handling in the finance module by adding sorting capabilities and refining the filtering options. The most important changes include the addition of a new `TransactionsSorting` type, updates to the `getTransactionsByTimeRange` function to support sorting, and modifications to the database query to incorporate the new sorting logic.
Enhancements to transaction handling:
* [`src/app/api/finance/actions.ts`](diffhunk://#diff-260fbe41f4f7257f0b40b2ac6e41078ab166248e43cedc83d828118c9c42fe25R19): Added `TransactionsSorting` to the import statements and updated the `getTransactionsByTimeRange` function to accept an optional sorting parameter. [[1]](diffhunk://#diff-260fbe41f4f7257f0b40b2ac6e41078ab166248e43cedc83d828118c9c42 …

Add limit & sorting functionality to transaction retrieval

---

.github/workflows/node.js.yml

add automatic build check when publishing

---

README.md

This pull request includes several updates to the `README.md` file to streamline the instructions and remove redundant information.
* Removed multiple ways to run the development server, keeping only `pnpm dev` for simplicity.
* Removed sections about editing the page and font optimization to focus on essential instructions.
* Updated the AI features section to use a more descriptive placeholder for the API key.
* Removed the deployment section for Vercel to keep the README concise.

update README for improved clarity & remove unnecessary instructions

---

src/app/(product)/page.tsx
src/app/api/journal/actions.ts
src/app/api/journal/db.ts
src/app/api/journal/types.ts
src/db/schema.ts

closes #113 
This pull request introduces several significant changes to the journal tagging system, including the addition of new functionalities for attaching and detaching tags from journals, as well as updates to the database schema and related functions.
* Added `attachTagToJournal` and `detachTagFromJournal` functions to handle the association and dissociation of tags with journals in `src/app/api/journal/actions.ts`.
* Introduced a new `journalsToTags` table to manage the many-to-many relationship between journals and tags in `src/db/schema.ts`.
* Updated the `tagsTable` to replace the `journalingTagsTable` and adjusted related functions accordingly in `src/app/api/journal/db.ts`. [[1]](diffhunk://#diff-aa745fefc3d82368c2a6b505e76c5ef2b5d090fc949d78376d4bb9a01ffb1e5aL154-R199) …

feat: implement journal tag management functions and update schema

---

src/app/(app)/journal/[id]/data.ts
src/app/api/journal/actions.ts
src/db/schema.ts
src/db/seed.ts

closes #115 
This pull request introduces several changes to enhance the journaling feature by adding new attributes and ensuring data consistency. The most important changes include updating the database schema, modifying the data seeding process, and adjusting the journal data structure.
Enhancements to journaling feature:
* [`src/db/schema.ts`](diffhunk://#diff-4bccf0a85960664570150bcf86a66e64e825b88f02fe19c2e323e96f65e2d55fL75-R80): Added new integer columns `mood`, `energy`, and `productivity` to the `journalingTable`. Made the `title` column non-nullable.
* `src/app/(app)/journal/[id]/data.ts`: Updated the `journalData` array to include `mood`, `energy`, and `productivity` attributes. ([src/app/(app)/journal/[id]/data.tsR34-R36](diffhunk://#diff-86079f5e97efc55fbe2034b47de4baeedaa4b3 …

add mood energy productivity to journals

---

src/app/api/finance/actions.ts
src/app/api/finance/db.ts
src/app/api/types.ts

* Add function to update transactions
* Add category id to the return of getTransactionsByTimeRange
* Add function to delete transactions
closes #124 
This pull request includes several updates to the finance API, focusing on transaction management. The most significant changes involve adding new functions for updating and deleting transactions and modifying existing functions to support optional filters.
* [`src/app/api/finance/actions.ts`](diffhunk://#diff-260fbe41f4f7257f0b40b2ac6e41078ab166248e43cedc83d828118c9c42fe25R36-R53): Added `updateTransaction` and `deleteTransaction` functions to handle updating and deleting transactions with user authentication.
* [`src/app/api/finance/db.ts`](diffhunk://#diff-74195402edb16756990a0c66c714be374db2bd3b9bcc42902baf189d7b1a499aR23-R54): …

* Made filter at getTransactionByTimeRange optional

---

src/app/api/finance/db.ts

Fix category id is missing in transaction presets

---

src/app/api/finance/actions.ts
src/app/api/finance/db.ts

Remove unused getRecentSimilarTransactions function and its related code

---

src/components/category/component.client.tsx

Finish Category Updating

---

src/app/(app)/finance/[type]/card.client.tsx
src/app/(app)/finance/[type]/constants.ts
src/app/(app)/finance/[type]/page.tsx
src/app/(app)/finance/[type]/pagination.tsx
src/app/(app)/finance/[type]/type.ts
src/app/(app)/finance/transaction.tsx
src/components/category/context.tsx

Finish Finance Pages

---

src/app/(app)/finance/category/card.client.tsx
src/app/(app)/finance/category/page.tsx

Finish /category page, blocked on #154 for /category/id

Finish Category Page

---

src/actions/finance/db.ts
src/actions/utils.ts
src/app/(product)/page.tsx
src/app/api/dev/seed/route.ts
src/db/seed.ts

closes #164 
This pull request includes several changes to improve the database seeding process, refactor code for better readability, and update the `Home` page component. The most important changes include refactoring the `dbListTransactions` function parameters, updating the `Home` page component to be asynchronous, and enhancing the database seeding process to include user-specific data.
* [`src/db/seed.ts`](diffhunk://#diff-b5d11a091459ab8bea0bdea1e7fb822e7c8fa9ffafed1bfdc575f1bc5edda6f5L13-R34): Modified the seeding functions to accept a `user_id` parameter and return the seeded data. This change ensures that the seeded data is associated with a specific user and can be returned for further use. [[1]](diffhunk://#diff-b5d11a091459ab8bea0bdea1e7fb822e7c8fa9ffafed1bfdc575f1bc5edda6f5L1 …

Timerange not applying to listTransactions

---

src/app/(app)/journal/page.tsx

fix eslint

---

src/actions/finance/db.ts
src/actions/finance/types.ts
src/app/(app)/journal/page.tsx

- Enhanced TransactionsFilter to include a query for searching transaction labels.
- Updated dbListTransactions and dbGetTransactionsCount to support filtering by query.
- Reorganized imports in page.tsx for better readability.
- 
This pull request includes changes to the transaction filtering and journal page layout. The most important changes include adding a new filter option for transactions, updating the transaction count method, and reordering imports in the journal page file.
* [`src/actions/finance/db.ts`](diffhunk://#diff-08534d0891d84d90f276af9824a5c618bd25170cb37d07d4a6b1e7aa5e725a92R89-R91): Added a new filter option `query` to the `dbListTransactions` and `dbGetTransactionsCount` methods, allowing transactions to be filtered by a search query using the `ilike` operator. …

Add search functionality to transaction

---

src/actions/finance/actions.ts
src/actions/finance/db.ts

closes #186 
This pull request includes refactoring and minor adjustments to the `src/actions/finance` module, focusing on code consistency and parameter order standardization. The most important changes involve reordering parameters in database functions, simplifying function implementations, and fixing an import order issue.
* [`src/actions/finance/db.ts`](diffhunk://#diff-08534d0891d84d90f276af9824a5c618bd25170cb37d07d4a6b1e7aa5e725a92L218-R218): Reordered parameters in the `dbGetCategory` function to have `userId` as the first parameter, aligning with the convention used in other database functions.
* [`src/actions/finance/actions.ts`](diffhunk://#diff-5bfea48584825f98c3bb412845703d50978233c0619f8bba5c44d3427c4f86e9L83-R86): Simplified the `updateCurrency` function by reducing nested …

Fix getCategory does only return id

---

src/app/globals.css

Make buttons clickable by default

---

next.config.ts
src/app/(app)/dashboard/page.tsx
src/app/(app)/journal/[id]/summarize.tsx
src/app/(auth)/sign-in/page.client.tsx
src/app/(auth)/sign-up/page.client.tsx
src/middleware.ts

For authentication
Also fixes some other bugs

add middleware

---

src/app/(app)/journal/[id]/summarize.tsx

Fix overflow

---

src/actions/utils.ts
src/app/(app)/finance/page.tsx
src/app/(app)/journal/@sidebar/(journal)/[id]/journal-sidebar.client.tsx
src/app/(app)/journal/[id]/page.tsx
src/app/(app)/journal/page.tsx
src/app/(app)/sidebar.tsx
src/auth/actions.ts
src/safe-actions/authAction.ts

closes #207 
This pull request introduces several updates to improve code organization, enhance performance, and add minor UI animations. Key changes include replacing direct `auth` calls with the new `serverAuth` utility, reordering imports for better readability, and adding animations to specific UI components.
* Replaced direct `auth.api.getSession` calls with the new `serverAuth.getSession` utility in `src/actions/utils.ts`, `src/auth/actions.ts`, and `src/safe-actions/authAction.ts`. This centralizes session handling and leverages React's `cache` for improved performance. [[1]](diffhunk://#diff-491bef8ed06e31b2355bcac6456a50b18f9374870dee15baf6ada86f22a2d000L1-L9) [[2]](diffhunk://#diff-76e533ff6e5d3bc5f2ff960822a671e1f84b5886f3d8b8725b04ab448dbe52afR5-R12) …

Add loading overlay

---

src/actions/goals/db.ts
src/app/(app)/dashboard/page.tsx
src/app/(app)/goals/page.client.tsx
src/app/(app)/journal/[id]/page.tsx
src/app/(app)/journal/[id]/summarize.tsx
src/app/api/journal/[id]/summarize/route.ts
src/app/globals.css

Add summary animation
